services:
  - type: web
    name: mistake-book-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mistake-book-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: mistake-book-db
    databaseName: mistake_db
    user: postgres
    region: oregon